lib/imagination_squares_phoenix_web/router.ex
defmodule ImaginationSquaresPhoenixWeb.Router do
  use ImaginationSquaresPhoenixWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end


  scope "/", ImaginationSquaresPhoenixWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/drawings", DrawingController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ImaginationSquaresPhoenixWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ImaginationSquaresPhoenixWeb.Telemetry
    end
  end
end

lib/imagination_squares_phoenix_web/templates/page/index.html.eex
<%= if is_nil(@user) do %>
  Please log in so you can create imaginary worlds!
  <br>
  <a href="/session/new">Login</a>
<% else %>
  <p>Howdy, <%= @user.email %>!</p>

  <%= for drawing <- @user.drawings do %>
    <%= link drawing.name, to: Routes.drawing_path(@conn, :show, drawing) %><br>
  <% end %>

  <%= form_for @new_drawing, Routes.drawing_path(@conn, :create), fn f -> %>
  <label>
    Name: <%= text_input f, :name %>
  </label>

  <%= submit "Submit" %>
<% end %>

  <%= link("Log out", to: "/session", method: :delete) %>
<% end %>